services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - app_vendor:/var/www/html/vendor
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todo_network
    command: php artisan serve --host=0.0.0.0 --port=8000

  postgres:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_DB: todo_crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_crud"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - todo_network

volumes:
  postgres_data:
  app_vendor:

networks:
  todo_network:
    driver: bridge
